# Generated by Django 6.0.6 on 2026-06-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(blank=True, verbose_name='日記内容'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=100, verbose_name='日記タイトル'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='study_time',
            field=models.IntegerField(verbose_name='学習時間(分)'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='科目など'),
        ),
    ]
