# Generated by Django 6.0.6 on 2026-06-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_diary_favorite_alter_diary_content_alter_diary_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='お気に入り'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='お気に入り登録'),
        ),
    ]
