# Generated by Django 6.0.6 on 2026-06-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_studyrecord_favorite_alter_diary_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyrecord',
            name='study_time',
        ),
        migrations.RemoveField(
            model_name='studyrecord',
            name='subject',
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='お気に入り登録'),
        ),
        migrations.CreateModel(
            name='StudyRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='科目など')),
                ('study_time', models.PositiveIntegerField(help_text='分', verbose_name='学習時間(分)')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='record.studyrecord')),
            ],
        ),
    ]
